ThesisManager.Web/Models/Shared/ConfirmDialogViewModel.cs
namespace ThesisManager.Web.Models.Shared {
    using System;

    /// <summary>
    ///     Bildet das VM für eine Bestätigung ab.
    /// </summary>
    public class ConfirmDialogViewModel {
        /// <summary>
        ///     Erstellt ein neues VM für die Bestätigung
        /// </summary>
        /// <param name="id"></param>
        /// <param name="title"></param>
        /// <param name="confirmationText"></param>
        /// <param name="controller"></param>
        /// <param name="action"></param>
        public ConfirmDialogViewModel(Guid id, string title, string confirmationText, string controller, string action) {
            Action = action;
            Controller = controller;
            Id = id;
            Title = title;
            ConfirmationText = confirmationText;
        }

        /// <summary>
        ///     Ruft den Namen der ActionMethode ab, die beim Bestätigen aufgerufen wird.
        /// </summary>
        public string Action { get; private set; }

        /// <summary>
        ///     Ruft den Text ab, den der Nutzer bestätigen muss/soll.
        /// </summary>
        public string ConfirmationText { get; private set; }

        /// <summary>
        ///     Ruft den Namen des Controllers ab, auf dem die Action(-Methode) beim Bestätigen aufgerufen wird.
        /// </summary>
        public string Controller { get; private set; }

        /// <summary>
        ///     Ruft die Id des Objektes ab, für welches die Bestätigung erfolgen soll.
        /// </summary>
        public object Id { get; private set; }

        /// <summary>
        ///     Ruft den Titel des bestätigen Dialoges ab.
        /// </summary>
        public string Title { get; private set; }
    }
}

ThesisManager.Web/Models/Shared/ErrorViewModel.cs
namespace ThesisManager.Web.Models.Shared {
    
    /// <summary>
    /// ViewModel für eine Fehleransicht, auf der eine Überschrift für einen Fehler und eine Beschreibung des Fehlers angezeigt werden.
    /// </summary>
    public class ErrorViewModel {

        public ErrorViewModel(string errorMessage) {
            ErrorTitle = "Fehler";
            ErrorMessage = errorMessage;
        }

        public ErrorViewModel(string errorTitle, string errorMessage) {
            ErrorTitle = errorTitle;
            ErrorMessage = errorMessage;
        }

        /// <summary>
        /// Ruft den Titel des Fehlers ab. 
        /// </summary>
        public string ErrorTitle { get; private set; }

        /// <summary>
        /// Ruft den anzuzeigenden Fehlertext ab.
        /// </summary>
        public string ErrorMessage { get; private set; }
    }
}

ThesisManager.Web/Models/Shared/MessageViewModel.cs
namespace ThesisManager.Web.Models.Shared {
    /// <summary>
    /// ViewModel für eine MessageView (egal ob Partial oder nicht), die einen Hinweis und einen Titel anzeigt.
    /// </summary>
    public class MessageViewModel {

        public MessageViewModel(string title, string message) {
            Title = title;
            Message = message;
        }

        /// <summary>
        /// Ruft den Titel der Hinweisseite ab.
        /// </summary>
        public string Title { get; private set; }

        /// <summary>
        /// Ruft den anzuzeigenden Hinweistext ab.
        /// </summary>
        public string Message { get; private set; }
    }
}

ThesisManager.Web/Controllers/ApplicationController.cs
namespace ThesisManager.Web.Controllers {
    using System.Collections.Generic;
    using System.Web.Mvc;

    using ThesisManager.Web.Models.Menu;

    /// <summary>
    /// Controller für alles was die Anwendung selbst betrifft. Zb. "Über", "Kontakt", etc.
    /// </summary>
    public class ApplicationController : BaseController {
        /// <summary>
        /// Über-Seite.
        /// </summary>
        /// <returns></returns>
        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        /// <summary>
        /// Kontakt-Seite.
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        /// <summary>
        /// Index-Seite
        /// </summary>
        /// <returns></returns>
        public ActionResult Index() {
            return View();
        }

        /// <summary>
        ///     Methode die das Hauptmenü rendert/liefert.
        ///     Dazu wird anhand der Rechte überprüft, was der Nutzer darf und das Menü dementsprechend angepasst.
        /// </summary>
        /// <returns></returns>
        public ActionResult MenuPartial() {
            ActionUrl activeLink = GetActiveLink();

            IList<MenuItemViewModel> menuModel = new List<MenuItemViewModel>();

            MenuViewModel menuViewModel = new MenuViewModel(menuModel);

            return View("MenuPartial", menuViewModel);
        }
    }
}

ThesisManager.Web/Controllers/ThesisController.cs
namespace ThesisManager.Web.Controllers {
    using System.Web.Mvc;

    /// <summary>
    /// Controller für alles was Abschlussarbeiten betrifft.
    /// </summary>
    public class ThesisController:BaseController {
        /// <summary>
        /// Liefert die Index-Seite.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index() {
            return null;
        }


    }
}

ThesisManager.Web/Controllers/UserController.cs
namespace ThesisManager.Web.Controllers {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using ThesisManager.Core.Domain;
    using ThesisManager.Core.Service;
    using ThesisManager.Web.Models.User;

    /// <summary>
    ///     Controller für alles was Nutzer betrifft.
    /// </summary>
    public class UserController : CrudController {
        /// <summary>
        ///     Liefert oder setzt den <see cref="IUserService" />.
        /// </summary>
        public IUserService UserService { get; set; }

        /// <summary>
        ///     Liefert die Nutzer-erstellen-Seite.
        /// </summary>
        /// <param name="login">Der Login von dem LDAP-Nutzer, zu dem ein DB-Eintrag generiert werden soll</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create(string login) {
            try {
                User user = UserService.Get(login);

                UserViewModel viewModel = new UserViewModel(user);

                return View("CreateUser", viewModel);
            } catch (Exception ex) {
                return ModalError(OnCreateException(ex));
            }
        }

        /// <summary>
        ///     Liefert eine PartialView, auf der alle Domain-Objekte des Typs <see cref="User" /> angezeigt werden.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public virtual ActionResult Grid() {
            try {
                IList<UserListModel> users = UserService.GetAll().Select(u => new UserListModel(u)).ToList();
                return PartialView("ListUsers", users);
            } catch (Exception ex) {
                Logger.Error(string.Format("Fehler beim Anzeigen aller Elemente vom Typ {0} in der Grid-Ansicht.", typeof(User)), ex);
                throw;
            }
        }
    }
}

ThesisManager.Web/Views/Shared/ConfirmOverlay.cshtml
@model ThesisManager.Web.Models.Shared.ConfirmDialogViewModel

@{
    Layout = "~/Views/Shared/_ModalLayout.cshtml";
    ViewBag.Title = Model.Title;
    ViewBag.SubmitTitle = "OK";
}

@using (Html.BeginForm(Model.Action, Model.Controller, new { id = Model.Id }, FormMethod.Post, new { role = "form", @class = "form-horizontal" })) {
    @Html.AntiForgeryToken()
    @Html.DisplayFor(m => m.ConfirmationText)
}

@* ReSharper disable once Razor.SectionNotResolved *@
@section PageId{
    Confirm_Overlay
}

ThesisManager.Web/Views/Shared/ErrorAlert.cshtml
@using ThesisManager.Web.Controllers
@if (TempData.ContainsKey(BaseController.ERROR_ALERT_KEY)) {
    <div class="alert alert-danger fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true"></span>
            <span class="sr-only"></span>
        </button>
        @TempData[BaseController.ERROR_ALERT_KEY]
    </div>
}

ThesisManager.Web/Views/Shared/ErrorOverlay.cshtml
@model ThesisManager.Web.Models.Shared.ErrorViewModel


@{
    ViewBag.Title = Model.ErrorTitle;
    Layout = "_ModalLayout.cshtml";
}

@Html.DisplayFor(m => m.ErrorMessage)

@section Footer {
    <button type="button" class="btn btn-default" onclick="modal.hideModalDiv() ">
        OK
    </button>
}

@* ReSharper disable once Razor.SectionNotResolved *@
@section PageId{
    Error_Overlay
}

ThesisManager.Web/Views/Shared/ErrorPartial.cshtml
@model ThesisManager.Web.Models.Shared.ErrorViewModel

<span class="danger">@Model.ErrorMessage</span>

ThesisManager.Web/Views/Shared/MenuPartial.cshtml
@model ThesisManager.Web.Models.Menu.MenuViewModel
           
@{
    Layout = null;
}

@Html.DisplayFor(m => m.MenuItems)

ThesisManager.Web/Views/Shared/Message.cshtml
@model ThesisManager.Web.Models.Shared.MessageViewModel

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>@Model.Message</p>

ThesisManager.Web/Views/Shared/MessageAlert.cshtml
@using ThesisManager.Web.Controllers
@if (TempData.ContainsKey(BaseController.MESSAGE_ALERT_KEY)) {
    <div class="alert alert-info fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true"></span>
            <span class="sr-only">Schließen</span>
        </button>
        @TempData[BaseController.MESSAGE_ALERT_KEY]
    </div>
}

ThesisManager.Web/Views/Shared/MessageOverlay.cshtml
@model ThesisManager.Web.Models.Shared.MessageViewModel


@{
    ViewBag.Title = Model.Title;
    Layout = "_ModalLayout.cshtml";
}

@Html.DisplayFor(m => m.Message)

@section Footer {
    <button type="button" class="btn btn-default" onclick="modal.hideModalDiv() ">
        OK
    </button>
}

@* ReSharper disable once Razor.SectionNotResolved *@
@section PageId{
    Message_Overlay
}

ThesisManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abschlussarbeiten-Verwaltung</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Abschlussarbeiten-Verwaltung", "Index", "Thesis", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Startseite", "Index", "Thesis")</li>
                    <li>@Html.ActionLink("Nutzer", "Grid", "User")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Application")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Abschlussarbeiten-Verwaltung</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ThesisManager.Web/Views/Shared/_ModalLayout.cshtml
@{
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}

<div class="modal-dialog" id="@Page.Session.SessionID.ToString()">
    <div class="modal-content" id="modal-div">
        <div class="modal-header">
            <button type="button" class="close" onclick="modal.hideModalDiv()" aria-hidden="true">
                &times;
            </button>
            <h4 class="modal-title">@ViewBag.Title</h4>
        </div>
        <div class="modal-body">
            @RenderBody()
        </div>
        <div class="modal-footer">
            @if (IsSectionDefined("Footer")) {
                @RenderSection("Footer")
            } else {
                if (string.IsNullOrEmpty(ViewBag.CancelTitle)) {
                    ViewBag.CancelTitle = "Abbrechen";
                }
                if (string.IsNullOrEmpty(ViewBag.SubmitTitle)) {
                    ViewBag.SubmitTitle = "OK";
                }

                <button type="button" class="btn btn-default" onclick="modal.hideModalDiv() ">
                    @ViewBag.CancelTitle
                </button>
                <button type="submit" class="btn btn-primary">
                    @ViewBag.SubmitTitle
                </button>
            }
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/hint")
@Scripts.Render("~/bundles/modal-buttons")
@Scripts.Render("~/bundles/bootstrap-datepicker")